CREATE TABLE IF NOT EXISTS users (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    is_seller BOOLEAN DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS products (
    id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description LONG VARCHAR,
    price DECIMAL(10,2) NOT NULL,
    seller_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL DEFAULT 0,
    FOREIGN KEY (seller_id) REFERENCES users(id)
);

-- Derby doesn't support GRANT statements
-- GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO interview1;